/**
 * Cooperative scheduling for the boot sequence (pattern borrowed from morning-diner's
 * core/scheduler.ts): the world is generated by many synchronous builders; run back to back they
 * would freeze the tab and the loading screen would never paint. The boot pipeline awaits
 * `yieldToPaint()` between tasks and reports weighted progress.
 */

export function yieldToPaint(): Promise<void> {
  return new Promise((resolve) => {
    let done = false;
    const finish = () => {
      if (done) return;
      done = true;
      resolve();
    };
    requestAnimationFrame(() => setTimeout(finish, 0));
    // Hidden tabs get no animation frames; keep the pipeline moving there.
    setTimeout(finish, 100);
  });
}

export type ProgressListener = (fraction: number, label: string) => void;

export class Progress {
  private parts = new Map<string, { weight: number; done: number }>();
  private total = 0;

  constructor(weights: Record<string, number>, private listener: ProgressListener) {
    for (const [k, w] of Object.entries(weights)) {
      this.parts.set(k, { weight: w, done: 0 });
      this.total += w;
    }
  }

  set(part: string, fraction: number, label: string) {
    const p = this.parts.get(part);
    if (!p) return;
    p.done = Math.max(p.done, Math.min(1, fraction));
    let sum = 0;
    for (const q of this.parts.values()) sum += q.weight * q.done;
    this.listener(sum / this.total, label);
  }
}

/** Runs a list of named steps, yielding to the browser between them. */
export async function runSteps(
  steps: { name: string; label: string; weight: number; run: () => void | Promise<void> }[],
  listener: ProgressListener,
): Promise<void> {
  const weights: Record<string, number> = {};
  for (const s of steps) weights[s.name] = s.weight;
  const progress = new Progress(weights, listener);
  for (const s of steps) {
    progress.set(s.name, 0, s.label);
    await yieldToPaint();
    const t0 = performance.now();
    await s.run();
    const dt = performance.now() - t0;
    if (import.meta.env.DEV) console.debug(`[boot] ${s.name} ${dt.toFixed(0)} ms`);
    progress.set(s.name, 1, s.label);
  }
}
